version: "3.9"

services:
  front_end:
    build:
      context: ./APP
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network

  data_base:
    build:
      context: ./Data_Base
    container_name: Data_Base_Gabo
    environment:
      MYSQL_PASSWORD: Gabo
      MYSQL_DATABASE: Base_Gabo
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge


