version: "3.9"

services:
  front_end:
    build:
      context: ./APP
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - data_base

  data_base:
    build:
      context: ./Data_Base
    container_name: Data_Base_Gabo
    environment:
      DB_HOST: data_base
      DB_DATABASE: Gabo_base
      DB_USER: root
      DB_PASSWORD: Gabo
    ports:
      - "3306:3306"
    volumes:
      - ./Data_base/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge


