version: "3.9"

services:
  app:
    build:
      context: ./APP
      dockerfile: Dockerfile
    volumes:
      - ./APP/Front_End/static:/APP/Front_End/static
      - ./APP/Front_End/templates:/APP/Front_End/templates
    expose:
      - "8000"
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Le proxy Nginx sera accessible depuis l'extérieur sur le port 80
    networks:
      - app_network
    depends_on:
      - app

  data_base:
    build:
      context: ./Data_Base
    container_name: Data_Base_Gabo
    environment:
      DB_HOST: data_base
      DB_DATABASE: Gabo_base
      DB_USER: root
      DB_PASSWORD: Gabo
    ports:
      - "3306:3306"
    volumes:
      - ./Data_base/init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backup:
    build:
      context: ./Backup
      dockerfile: Dockerfile
    volumes:
      - ./Backup/back_up:/Backup/back_up
    expose:
      - "8080"
    networks:
      - app_network
    depends_on:
      data_base:
        condition: service_healthy

networks:
  app_network:
    driver: bridge



