# Deployment for the "api-rules" service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rules
  labels:
    app: api-rules
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rules
  template:
    metadata:
      labels:
        app: api-rules
    spec:
      containers:
      - name: api-rules
        image: lagadglav/gabo-api-rules:latest
        ports:
          - containerPort: 8030
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          - name: api-rules-volume
            mountPath: /API-RULES
          - name: utils-volume
            mountPath: /utils
          - name: kaggle-config-volume
            mountPath: /root/.config/kaggle
            readOnly: true
      volumes:
        - name: api-rules-volume
          emptyDir: {}
        - name: utils-volume
          emptyDir: {}
        - name: kaggle-config-volume
          emptyDir: {}
