apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Baptiste Fougeray\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api-add-game
  name: api-add-game
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-add-game
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Baptiste Fougeray\kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: api-add-game
    spec:
      containers:
        - image: api-add-game
          name: api-add-game
          ports:
            - containerPort: 8020
              protocol: TCP
          volumeMounts:
            - mountPath: /API-AG
              name: api-add-game-claim0
            - mountPath: /utils
              name: api-add-game-claim1
      restartPolicy: Always
      volumes:
        - name: api-add-game-claim0
          persistentVolumeClaim:
            claimName: api-add-game-claim0
        - name: api-add-game-claim1
          persistentVolumeClaim:
            claimName: api-add-game-claim1
