apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Baptiste Fougeray\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api-add-game
  name: api-add_game
spec:
  ports:
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: api-add-game
