# Service for the "api-add-game" service
apiVersion: v1
kind: Service
metadata:
  name: api-add-game-service
  labels:
    app: api-add-game
spec:
  selector:
    app: api-add-game
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
  type: ClusterIP
