# Deployment for the "backup" service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup
  labels:
    app: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
  template:
    metadata:
      labels:
        app: backup
    spec:
      containers:
      - name: backup
        image: lagadglav/gabo-backup:latest
        env:
          - name: PYTHONPATH
            value: "/API-AP:/utils"
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - name: backup-volume
            mountPath: /Backup/back_up
      volumes:
        - name: backup-volume
          emptyDir: {}
