apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-base
  labels:
    app: data-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-base
  template:
    metadata:
      labels:
        app: data-base
    spec:
      containers:
        - name: data-base
          image: lagadglav/Gabo-data-base:latest  # Doit contenir init.sql dans /docker-entrypoint-initdb.d/
          env:
            - name: DB_HOST
              value: "data-base"
            - name: DB_DATABASE
              value: "Gabo_base"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Gabo"
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
