apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Baptiste Fougeray\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: data-base
  name: data-base
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-base
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Baptiste Fougeray\kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: data-base
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: Gabo_base
            - name: DB_HOST
              value: data_base
            - name: DB_PASSWORD
              value: Gabo
            - name: DB_USER
              value: root
          image: data-base
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          name: data-base-gabo
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: data-base-claim0
            - mountPath: /var/lib/mysql
              name: data-base-tmpfs0
      restartPolicy: Always
      volumes:
        - name: data-base-claim0
          persistentVolumeClaim:
            claimName: data-base-claim0
        - emptyDir:
            medium: Memory
          name: data-base-tmpfs0
