apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: my-app
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: lagadglav/database:latest
          env:
            - name: DB_HOST
              value: "data_base"
            - name: DB_DATABASE
              value: "Gabo_base"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Gabo"
          ports:
            - containerPort: 3306
