name: Déployer sur Raspberry Pi (password SSH)

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt GitHub
        uses: actions/checkout@v3

      - name: Déploiement sur Raspberry Pi via SSH (avec mot de passe)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RASPBERRY_IP }}
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          port: 22 
          script: |
            echo "Début du déploiement..."
            # Définit le répertoire et l'URL du dépôt
            REPO_DIR="/home/gabo/hebergement" 
            REPO_URL="https://github.com/Lagadglav/Gabo_Dev.git"

            # Si le dossier n'existe pas, clone le dépôt, sinon fait un pull
            if [ ! -d "$REPO_DIR" ]; then
              echo "Dépôt non trouvé, clonage en cours..."
              git clone $REPO_URL $REPO_DIR || { echo "Echec du clonage"; exit 1; }
            fi

            cd $REPO_DIR
            echo "Mise à jour du dépôt..."
            git pull origin production

            echo "Stoppping previous compose"
            docker-compose down
            
            echo "Mise à jour des images Docker..."
            docker-compose pull

            echo "Relance de Docker Compose..."
            docker-compose up -d

            echo "Déploiement terminé."
